### PR TITLE
NCR and Legion Balance 

### PR DESCRIPTION
**Pull request by SeeminglyTypicalUsername**
## About The Pull Request

Decreases the power level of the Legion and NCR and replaces most loadouts with Gunboxes (randomized loot containers)
image

## Why It's Good For The Game

Removes the meta of picking particular loadouts, increases gun variety in play, and partially fixes the issues with Wasteland balancing (the other factions and the map itself will need to be balanced) 

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: gunboxes
add: NCR dress coat for the captain
tweak: replaces most NCR/Legion loadouts with gunboxes
balance: lowers NCR and legion power level.
/:cl:

### CODE REVIEW

**Comment by ZAB909** [comment]
Having random loadouts is fucking aids HELLL NO. What if I wanna shotgun or snipe? Guess im fucked. -1

**Comment by Kitsunemitsu** [comment]
Personally, I think that people will just respawn until they get the one they want, but I'm okay with this.

**Comment by TripleShades** [comment]
This made sure to leave in faction-specific guns, correct? Also, NCR wont be getting Legion-flavored guns and vice-versa, right?

**Comment by SeeminglyTypicalUsername** [comment]
> This made sure to leave in faction-specific guns, correct? Also, NCR wont be getting Legion-flavored guns and vice-versa, right?

It's role specific.

**Comment by Kitsunemitsu** [comment]
I'm approving. I hope my fears are unfounded

**Pull request merged**
