### PR TITLE
Peasant update

### PR DESCRIPTION
**Pull request by SeeminglyTypicalUsername**
## About The Pull Request

Gives the peasants a little more attention: 
image
image

## Why It's Good For The Game

More solo content

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: More supplies
add: Bees
tweak: Different animals 
/:cl:

### CODE REVIEW

**Review by hermaplusplus — CHANGES_REQUESTED** [review]
Your commit includes undocumented reversions of other commits (e.g. [`d0ef790`](https://github.com/StoneAndStar/RockStar/pull/9/commits/d0ef790e9d1b523e097510d3821e593ec8fd0d83). I'm unsure of how far back these implicit reversions go, but I assume it has something to do with PR #46. This must be addressed for this PR to be merged.

**Comment by TripleShades** [comment]
Okay, but did you test the bees?
Do they actually work? Or is the queen instantly being deleted once put into the hive?

**Comment by hermaplusplus** [comment]
> Okay, but did you test the bees? Do they actually work? Or is the queen instantly being deleted once put into the hive?

@TripleShades I have not tested it, no. I noticed a failing check and the compilation error displayed was identical to another recent error, which was rectified by [`d0ef790`](https://github.com/StoneAndStar/RockStar/pull/9/commits/d0ef790e9d1b523e097510d3821e593ec8fd0d83). Until the implicit reversions are removed, the PR will be neither testmerged nor merged.

**Comment by TripleShades** [comment]
@hermaplusplus I was not asking you, I was asking the mapper, @SeeminglyTypicalUsername
It wouldn't be a very good thing to map in objects that straight up do not function, or objects that you do not know the purpose of (in some cases, not this specific one.)

**Comment by hermaplusplus** [comment]
> @hermaplusplus I was not asking you, I was asking the mapper, @SeeminglyTypicalUsername It wouldn't be a very good thing to map in objects that straight up do not function, or objects that you do not know the purpose of (in some cases, not this specific one.)

My bad, I assumed you were replying to the comment directly above.

**Comment by SeeminglyTypicalUsername** [comment]
> Your commit includes undocumented reversions of other commits (e.g. [`d0ef790`](https://github.com/StoneAndStar/RockStar/pull/9/commits/d0ef790e9d1b523e097510d3821e593ec8fd0d83). I'm unsure of how far back these implicit reversions go, but I assume it has something to do with PR #46. This must be addressed for this PR to be merged.

I'll just redo this later.

**Pull request closed without merging**
